steps:
# Build and deploy Stack Overflow service
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', 'stackoverflow-service', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/assignment5-20502179/stackoverflow-service:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/assignment5-20502179/stackoverflow-service:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'stackoverflow-service', '--image', 'gcr.io/assignment5-20502179/stackoverflow-service:$COMMIT_SHA', '--platform', 'managed', '--region', 'us-central1']

# Build and deploy GitHub service
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', 'github-service', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/assignment5-20502179/github-service:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/assignment5-20502179/github-service:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'github-service', '--image', 'gcr.io/assignment5-20502179/github-service:$COMMIT_SHA', '--platform', 'managed', '--region', 'us-central1']

images:
- 'gcr.io/assignment5-20502179/stackoverflow-service:$COMMIT_SHA'
- 'gcr.io/assignment5-20502179/github-service:$COMMIT_SHA'
